language: python

python:
  - "3.7"

jobs:
  include:
  - stage: test
    install:
      - pip install -r dev-requirements.txt
      - pip install -r requirements.txt
    script:
      - python -m pytest --cov=. tests/
    after_success:
      - coverage report
      - coveralls
  - stage: deploy
    if: branch = master AND (NOT type IN (pull_request))
    before_install:
    - nvm install lts/* --latest-npm
    python:
    - "3.7"
    install:
    - pip install -r dev-requirements.txt
    - pip install -r requirements.txt
    - npm install @semantic-release/exec
    script:
    - git config --global user.email "releases@ladybug.tools"
    - git config --global user.name "ladybugbot"
    - pip install -U .
    - npx semantic-release
  - stage: docs
    if: tag IS present
    install:
    - pip install -r dev-requirements.txt
    - pip install -r requirements.txt
    - npm install -g redoc-cli
    script:
    - export CLEAN_TAG=$(echo $TRAVIS_TAG | sed 's/v//g')
    - python docs.py --version $CLEAN_TAG
    - redoc-cli bundle ./docs/model_inheritance.json -o ./docs/model.html
    deploy:
      on:
        tags: true
      provider: pages
      skip_cleanup: true
      github-token: $GH_TOKEN
      keep-history: false
      local_dir: docs/
